apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    env: dev
spec:
  template:
    metadata:
      labels:
        # 기존 app: my-node-app 라벨은 그대로 두고, "test" 라벨 값을 변경합니다.
        test: "patched"
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
        # 추가 어노테이션을 통해 patch가 적용되었음을 표시합니다.
        patched: "true"
    spec:
      containers:
      - name: my-node-app
        # 컨테이너에 임의의 환경 변수 추가 (Pod description에서 환경 변수 항목으로 확인 가능)
        env:
        - name: MY_PATCHED_ENV
          value: "patched"

