apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: my-node-app
        image: 058264243522.dkr.ecr.ap-northeast-2.amazonaws.com/daleyoo/simeple_app
        imagePullPolicy: Always

